/*
https://leetcode.com/problems/find-the-difference/description/?envType=problem-list-v2&envId=v3of1sph

You are given two strings s and t.
String t is generated by random shuffling string s and then add one more letter at a random position.
Return the letter that was added to t.

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"
*/

#include<bits/stdc++.h>
using namespace std;

int main(){
    string s;
    cout<<"Enter the s string: "<<endl;
    cin>>s;

    string t;
    cout<<"Enter the t string: "<<endl;
    cin>>t;
    
    vector<int> freq(256, 0);

    for(char c : t) freq[c]++;
    for(char c : s) freq[c]--;

    for(int i = 0; i < 256; i++){
        if(freq[i] > 0){
            cout << char(i);
            return 0;
        }
    }

}